[![](https://mermaid.ink/img/pako:eNpVkM1qw0AMhF9F6NRC_AI-FBq7zSWlhebmzUF45eyS7A9rmRBsv3vXNoVWJzHzjRAzYhs0Y4ndLdxbQ0ngVCsPeV6byiTbi6P-DEXxMh1YwAXPjwn2T4cAvQkxWn953vj9AkE1HheMQYz113mzqjX_6XmCujlSlBDPf53TPUzw1tgvk8__d0zinHpvOio7KlpKUFFaEdyh4-TI6vz-uCgKxbBjhWVeNXc03ESh8nNGaZDw_fAtlpIG3uEQNQnXli6J3K_I2kpIH1sjazHzDwZeXUA?type=png)](https://mermaid.live/edit#pako:eNpVkM1qw0AMhF9F6NRC_AI-FBq7zSWlhebmzUF45eyS7A9rmRBsv3vXNoVWJzHzjRAzYhs0Y4ndLdxbQ0ngVCsPeV6byiTbi6P-DEXxMh1YwAXPjwn2T4cAvQkxWn953vj9AkE1HheMQYz113mzqjX_6XmCujlSlBDPf53TPUzw1tgvk8__d0zinHpvOio7KlpKUFFaEdyh4-TI6vz-uCgKxbBjhWVeNXc03ESh8nNGaZDw_fAtlpIG3uEQNQnXli6J3K_I2kpIH1sjazHzDwZeXUA)
